name: Comment Branch Name on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Comment Branch Name
        uses: unsplash/comment-on-pr@v1
        with:
          message: "This pull request is associated with the branch: ${{ github.head_ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
